name: 🚀 Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - run: mvn clean compile -q
    - run: mvn package -DskipTests -q
    - run: echo "✅ Build realizado com sucesso! JAR disponível em target/"